import {describe,it,expect} from 'vitest';import {matchOpportunity,opportunityMatchesFilters} from '../src/lib/matching';import type {Opportunity,Preferences} from '../src/types';
const o={id:'1',slug:'robotics',title:'Robotics',organization:'Pioneer',category:'School',subcategory:'STEM',audience:'Pioneer students',eligibility:'Pioneer students in grades 9–12',status:'open',nextAction:null,deadlineText:null,schedule:'After school',effort:'2–5 hours',cost:'Free',compensation:'Unpaid',format:'In person',location:'Pioneer High School',transportation:'On campus',requirements:null,summary:'Build robots.',interestTags:['Robotics'],sourceUrl:'https://example.org',sourceType:'Official',lastVerified:'2026-08-25',confidence:'High',notes:null,published:true,importBatch:'x',sourceRow:4} satisfies Opportunity;
const p={query:'robotics',categories:[],freeOnly:true,paid:false,onCampus:true,verifiedOnly:true,grade:'10'} satisfies Preferences;
describe('matching',()=>{it('classifies known passing requirements exact',()=>expect(matchOpportunity(o,p).classification).toBe('exact'));it('treats unknown as likely, not exact',()=>expect(matchOpportunity({...o,eligibility:null},p).classification).toBe('likely'));it('does not let keywords override a closed listing',()=>expect(matchOpportunity({...o,status:'closed'},p).classification).toBe('near'));it('excludes categories that were not selected',()=>expect(opportunityMatchesFilters(o,{...p,categories:['Community']},[],'')).toBe(false));it('matches any selected interest',()=>expect(opportunityMatchesFilters(o,{...p,categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Robotics','Writing'],'')).toBe(true));it('does not treat citizen science as computer science',()=>expect(opportunityMatchesFilters({...o,title:'Park survey',subcategory:'Parks / environment',summary:'A citizen-science stewardship role.'},{...p,query:'',categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Computer science'],'')).toBe(false));it('ignores excluded interests in eligibility text',()=>expect(opportunityMatchesFilters({...o,title:'Engineering scholarship',subcategory:'Engineering',summary:'Scholarship for future engineers.',eligibility:'Computer science excluded'},{...p,query:'',categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Computer science'],'')).toBe(false));it('maps UAS4STEM to both robotics and computer science',()=>{const uas={...o,title:'Scio Flyers UAS4STEM Drone Engineering Challenge',subcategory:'Aviation / engineering',interestTags:['Robotics','Computer science']};expect(opportunityMatchesFilters(uas,{...p,query:'',categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Robotics'],'')).toBe(true);expect(opportunityMatchesFilters(uas,{...p,query:'',categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Computer science'],'')).toBe(true)});it('does not treat Civic Theatre as government',()=>expect(opportunityMatchesFilters({...o,title:'Front-of-house volunteer',organization:'Ann Arbor Civic Theatre',subcategory:'Theatre / ushering',summary:'Community theatre opportunity.'},{...p,query:'',categories:[],freeOnly:false,onCampus:false,verifiedOnly:false},['Government / civic engagement'],'')).toBe(false));});

describe('interest taxonomy audit',()=>{
 const neutral={...p,query:'',categories:[],freeOnly:false,paid:false,onCampus:false,verifiedOnly:false,grade:undefined};
 const matches=(changes:Partial<Opportunity>,interest:string)=>opportunityMatchesFilters({...o,interestTags:undefined,...changes},neutral,[interest],'');
 it('ignores generic university boilerplate for arts',()=>expect(matches({title:'Biomedical internship',subcategory:'Biomedical research',summary:'University-connected research, arts, leadership, or volunteer opportunity.'},'Arts')).toBe(false));
 it('does not interpret attendance as dance',()=>expect(matches({title:'Festival attendance tracker',subcategory:'Event data / evaluation volunteering'},'Dance')).toBe(false));
 it('does not interpret Rosa Parks as outdoors',()=>expect(matches({title:'Rosa Parks Scholarship',subcategory:'Scholarship'},'Outdoors')).toBe(false));
 it('does not interpret a dance company as sports',()=>expect(matches({title:'Dance performance company',subcategory:'Performance and competition company',summary:'Includes professional-sports halftime shows.'},'Sports')).toBe(false));
 it('does not use an organization name alone for music',()=>expect(matches({title:'Ballet technique',organization:'Academy of Dance & Music',subcategory:'Dance classes'},'Music')).toBe(false));
 it('does not use generic educational boilerplate for tutoring',()=>expect(matches({title:'River cleanup',subcategory:'Environment / river',summary:'Monitoring, cleanup, education, or outreach role.'},'Tutoring / education')).toBe(false));
 it('does not classify paid parks jobs as community service',()=>expect(matches({title:'City Parks summer counselor',category:'Paid Work/Internship',subcategory:'Paid summer job'},'Community service')).toBe(false));
 it('does not classify a generic community program as service',()=>expect(matches({title:'Drone Engineering Challenge',category:'Volunteer/Community',subcategory:'Aviation / engineering'},'Community service')).toBe(false));
 it('does not interpret Growing Hope as rowing',()=>expect(matches({title:'Growing Hope youth day',subcategory:'Food / environment'},'Sports')).toBe(false));
 it('uses explicit workbook tags instead of guessing from unrelated words',()=>expect(matches({title:'City election theatre event',subcategory:'Civic arts',interestTags:['Government / civic engagement']},'Theatre')).toBe(false));
 it('matches an explicit workbook tag',()=>expect(matches({title:'Technology program',subcategory:'STEM',interestTags:['Computer science']},'Computer science')).toBe(true));
 it('does not classify a health-system flower garden as medicine',()=>expect(matches({title:'The Farm at Trinity Health — flower garden',subcategory:'Environment'},'Medicine / health')).toBe(false));
 it('does not treat unpaid as paid',()=>expect(opportunityMatchesFilters({...o,compensation:'Unpaid / enrichment'},neutral,[],'')).toBe(true));
 it('rejects unpaid when the paid filter is selected',()=>expect(opportunityMatchesFilters({...o,compensation:'Unpaid / enrichment'},{...neutral,paid:true},[],'')).toBe(false));
});
