import {Link} from 'react-router-dom';

const content:Record<string,[string,string,string[]]>={
  about:['About this project','A local, student-built directory designed to make Pioneer opportunities easier to find and verify.',['The project is independent unless an official partnership is established.','Coverage prioritizes Pioneer, Ann Arbor, and accessible nearby programs.','The public web cannot establish a complete current Pioneer club roster. Counselors, advisers, and club leaders can help confirm it.']],
  methodology:['How matching works','Requirements are classified before results are ranked. Unknown never means pass.',['Exact Match: every known must-have passes and important eligibility facts are known.','Likely Match: nothing known fails, but at least one important fact is unknown.','Near Match: only one or two constraints fail, and the difference is explained.','Ranking then considers interests, urgency, location, schedule, effort, cost, and freshness. Current algorithm: 1.0.0.']],
  sources:['Sources and verification','Each listing keeps its public source, publisher, evidence confidence, and last verification date.',['We prefer APIs, feeds, calendars, exports, and provider submissions before permitted page monitoring.','We do not bypass authentication or scrape private student systems.','Listings checked within 45 days are marked recently checked, listings 46–90 days old are marked review soon, and older listings are marked needs rechecking. Age labels do not replace confirmation with the provider.','Student reports enter a private review queue and never change a listing automatically.']],
  privacy:['Privacy in plain language','You can browse without an account. The site collects as little student data as possible.',['We do not sell data, use targeted advertising, create public student profiles, or provide direct messaging.','Without an account, saved opportunity IDs stay in this tab session. Account saves are kept separately and are not copied into guest storage. If you sign in, we store your email, authentication records, saved opportunity IDs, and any application or participation status you voluntarily report.','Your account data is protected by per-user database access rules. Other students cannot view your email, saved list, or outcomes. Combined project metrics are visible only to the project owner.','Anonymous impact measurement is off until you allow it. If allowed, a temporary random session ID counts visits, page categories, saves, and official-source clicks without recording your email, search text, or selected filters. A daily cleanup removes events older than 12 months; removal may take up to 24 additional hours while the database is running.','Feedback and correction forms do not request a name or email. Written responses stay private for review, are removed by daily cleanup after 12 months, and combined feedback and correction totals are available only to the project owner.','Searches and sensitive eligibility or accessibility filters are processed in your browser and are not attached to your account.','You can decline impact measurement, clear browser saves, delete saved items, or permanently delete your account.','An official school launch requires legal and district privacy review; this independent site does not claim COPPA or FERPA compliance without that review.']],
  terms:['Terms of use','This directory summarizes public information for convenience.',['Always verify requirements, dates, costs, travel, and safety details with the official provider.','The site does not submit applications, guarantee eligibility, or promise accommodations.','Listings may be corrected, closed, or removed when evidence changes.']],
  accessibility:['Accessibility','The product targets WCAG 2.2 AA and supports keyboard, screen-reader, zoom, reflow, and reduced-motion use.',['Use the “Report outdated information” form to report an accessibility barrier.','Provider accessibility details are shown only when documented.','No listing should promise an accommodation the provider has not confirmed.']],
};

export default function Info({kind}:{kind:string}){
  const c=content[kind]||content.about;
  return <section className="prose"><p className="kicker">PIONEER OPPORTUNITY HUB</p><h1>{c[0]}</h1><p className="lede">{c[1]}</p>{c[2].map(x=><p key={x}>{x}</p>)}
    {kind==='about'&&<><section className="story-block"><h2>Why it exists</h2><p>Useful programs are scattered across school, college, nonprofit, government, and community websites. This project brings those public listings into one student-friendly place so a student can compare realistic options without already knowing where to look.</p></section><section className="story-block"><h2>What was built</h2><p>The work includes researching and organizing listings, documenting official sources, creating transparent matching and freshness rules, building private accounts and saves, and measuring aggregate outcomes without creating public student profiles.</p></section><section className="story-block"><h2>Independent and transparent</h2><p>This is a student-built project for the Pioneer community, not an official school service. Listings are summaries of provider information, not endorsements. Every student should confirm requirements and safety details with the official organization.</p><div className="actions"><Link className="button" to="/feedback">Give feedback</Link><Link className="button secondary" to="/sources">Read the verification process</Link></div></section></>}
    {kind==='privacy'&&<><h2>Services used</h2><div className="table-wrap"><table><thead><tr><th>Service</th><th>Purpose</th><th>Data involved</th></tr></thead><tbody><tr><td>Supabase</td><td>Email sign-in, private saves, voluntary outcomes, and aggregate impact counts</td><td>Email and authentication records for accounts; saved opportunity IDs and statuses; opt-in anonymous events</td></tr><tr><td>Firebase Hosting, GitHub Pages, and Vercel</td><td>Website hosting and delivery</td><td>Standard request and security information</td></tr></tbody></table></div><h2>Your choices</h2><p>Accounts and anonymous measurement are optional. You may use the site without signing in, decline measurement, export your saved list, clear browser saves, sign out everywhere, or delete your account. Questions or privacy requests can be submitted through the site’s correction form while a dedicated contact address is being established.</p></>}
  </section>;
}
