const content:Record<string,[string,string,string[]]>={
  about:['About this project','A local, student-built directory designed to make Pioneer opportunities easier to find and verify.',['The project is independent unless an official partnership is established.','Coverage prioritizes Pioneer, Ann Arbor, and accessible nearby programs.','The public web cannot establish a complete current Pioneer club roster. Counselors, advisers, and club leaders can help confirm it.']],
  methodology:['How matching works','Requirements are classified before results are ranked. Unknown never means pass.',['Exact Match: every known must-have passes and important eligibility facts are known.','Likely Match: nothing known fails, but at least one important fact is unknown.','Near Match: only one or two constraints fail, and the difference is explained.','Ranking then considers interests, urgency, location, schedule, effort, cost, and freshness. Current algorithm: 1.0.0.']],
  sources:['Sources and verification','Each listing keeps its public source, publisher, evidence confidence, and last verification date.',['We prefer APIs, feeds, calendars, exports, and provider submissions before permitted page monitoring.','We do not bypass authentication or scrape private student systems.','Stale or ambiguous listings are excluded from default publication until reviewed.']],
  privacy:['Privacy in plain language','You can browse without an account. The site collects as little student data as possible.',['We do not sell data, use targeted advertising, create public student profiles, or provide direct messaging.','Without an account, saved opportunity IDs stay in your browser. If you sign in, we store your email, authentication records, and saved opportunity IDs so your list can sync.','Your account data is protected by per-user database access rules. Other students cannot view your email or saved list.','Searches and sensitive eligibility or accessibility filters are processed in your browser and are not attached to your account.','You can delete saved items or permanently delete your account from the account page.','An official school launch requires legal and district privacy review; this independent site does not claim COPPA or FERPA compliance without that review.']],
  terms:['Terms of use','This directory summarizes public information for convenience.',['Always verify requirements, dates, costs, travel, and safety details with the official provider.','The site does not submit applications, guarantee eligibility, or promise accommodations.','Listings may be corrected, closed, or removed when evidence changes.']],
  accessibility:['Accessibility','The product targets WCAG 2.2 AA and supports keyboard, screen-reader, zoom, reflow, and reduced-motion use.',['Use the “Report outdated information” form to report an accessibility barrier.','Provider accessibility details are shown only when documented.','No listing should promise an accommodation the provider has not confirmed.']],
};

export default function Info({kind}:{kind:string}){
  const c=content[kind]||content.about;
  return <section className="prose"><p className="kicker">PIONEER OPPORTUNITY HUB</p><h1>{c[0]}</h1><p className="lede">{c[1]}</p>{c[2].map(x=><p key={x}>{x}</p>)}
    {kind==='privacy'&&<><h2>Services used</h2><div className="table-wrap"><table><thead><tr><th>Service</th><th>Purpose</th><th>Data involved</th></tr></thead><tbody><tr><td>Supabase</td><td>Email sign-in and private saved lists</td><td>Email, authentication records, saved opportunity IDs</td></tr><tr><td>GitHub Pages and Vercel</td><td>Website hosting and delivery</td><td>Standard request and security information</td></tr></tbody></table></div><h2>Your choices</h2><p>Accounts are optional. You may use the site without signing in, export your saved list, clear browser saves, sign out everywhere, or delete your account. Questions or privacy requests can be submitted through the site’s correction form while a dedicated contact address is being established.</p></>}
  </section>;
}
