import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import XLSX from 'xlsx'; import {z} from 'zod';
const args=process.argv.slice(2); const dryRun=args.includes('--dry-run'); const input=args.find(a=>!a.startsWith('--'));
if(!input) throw new Error('Usage: pnpm import:opportunities <workbook.xlsx> [--dry-run]');
const required=['ID','Opportunity','Host','Category','Status','Description','Source URL','Last verified','Confidence'];
const clean=(v:unknown)=>v==null?null:String(v).replace(/\s+/g,' ').trim()||null;
const slug=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
const canonical=(raw:string)=>{try{const u=new URL(raw);u.hash='';['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach(k=>u.searchParams.delete(k));u.hostname=u.hostname.toLowerCase();return u.toString().replace(/\/$/,'');}catch{return raw;}};
const mapStatus=(s:string)=>{const v=s.toLowerCase();if(/closed|past|expired|watch/.test(v))return'closed';if(/verify|historical|unclear/.test(v))return'verify';if(/upcoming|next cycle/.test(v))return'upcoming';if(/ongoing|rolling|year-round/.test(v))return'ongoing';return'open';};
const schema=z.object({id:z.string().min(1),title:z.string().min(2),organization:z.string().min(2),category:z.string().min(2),summary:z.string().min(5),sourceUrl:z.string().url(),lastVerified:z.string().min(8),confidence:z.enum(['High','Medium','Low'])});
const wb=XLSX.readFile(input,{cellDates:true}); const ws=wb.Sheets['Opportunities']; if(!ws)throw new Error('Missing Opportunities sheet');
const grid=XLSX.utils.sheet_to_json<unknown[]>(ws,{header:1,raw:false,defval:null}); const hi=grid.findIndex(r=>Array.isArray(r)&&r[0]==='ID'); if(hi<0)throw new Error('Could not find Opportunities header');
const headers=(grid[hi] as unknown[]).map(clean); const missing=required.filter(h=>!headers.includes(h)); if(missing.length)throw new Error(`Missing required columns: ${missing.join(', ')}`);
const batch=crypto.createHash('sha256').update(fs.readFileSync(input)).digest('hex').slice(0,16); const seen=new Set<string>(); const accepted:any[]=[]; const rejected:any[]=[]; const duplicates:any[]=[];
for(let i=hi+1;i<grid.length;i++){const row=grid[i] as unknown[]; if(!clean(row[0]))continue; const obj=Object.fromEntries(headers.map((h,j)=>[h||`_${j}`,clean(row[j])]));
 const sourceUrl=canonical(obj['Source URL']||''); const base={id:obj.ID,title:obj.Opportunity,organization:obj.Host,category:obj.Category,summary:obj.Description,sourceUrl,lastVerified:obj['Last verified'],confidence:obj.Confidence}; const valid=schema.safeParse(base); if(!valid.success){rejected.push({row:i+1,id:obj.ID,error:valid.error.issues.map(x=>x.message).join('; ')});continue;}
 const key=`${slug(base.organization||'')}|${slug(base.title||'')}|${sourceUrl}`; if(seen.has(key)){duplicates.push({row:i+1,id:base.id,key});continue;} seen.add(key);
 const status=mapStatus(obj.Status||'verify'); const interestTags=(obj['Interest tags']||'').split(/\s*;\s*/).filter(Boolean); if(/uas4stem/i.test(base.title||''))for(const tag of ['Robotics','Computer science'])if(!interestTags.includes(tag))interestTags.push(tag); accepted.push({...base,slug:`${slug(base.title||'')}-${slug(base.organization||'').slice(0,24)}`,subcategory:obj.Subcategory,audience:obj.Audience,eligibility:obj.Eligibility,status,nextAction:obj['Next action'],deadlineText:obj['Deadline/season'],schedule:obj['Schedule/hours'],effort:obj.Effort,cost:obj.Cost,compensation:obj.Compensation,format:obj.Format,location:obj.Location,transportation:obj.Transportation,requirements:obj.Requirements,interestTags,sourceType:obj['Source type']||'Unknown',notes:obj.Notes,published:status!=='verify'&&status!=='closed',importBatch:batch,sourceRow:i+1}); }
const report={input:path.resolve(input),batch,dryRun,accepted:accepted.length,publishable:accepted.filter(x=>x.published).length,rejected,duplicates}; console.log(JSON.stringify(report,null,2));
if(!dryRun){fs.mkdirSync('src/data',{recursive:true});fs.writeFileSync('src/data/opportunities.json',JSON.stringify(accepted,null,2)+'\n');fs.writeFileSync('src/data/import-report.json',JSON.stringify(report,null,2)+'\n');}
